### ISSUE TITLE
Никита, твоя TempFS не поддерживает запись по смещению!

### ISSUE THREAD

**Issue by NDRAEY** [pimnik98/SayoriOS#152]
**Describe the bug**
Например мы хотим записать слово Sayori по смещению 10 от начала файла.

```
FILE* fp = fopen("T:\\file.txt", "w");
fseek(fp, 10, SEEK_SET);
fwrite(fp, 6, 1, "Sayori");
fclose(fp);
```

Но код не работает потому что ФС не поддерживает  запись по смещению

Пример готовой программы скину позже

**Comment by pimnik98** [comment]
Хм, но в теории надо просто дописать реализацию.

Мол считать до 6 байт, если их нет, то заполнить 0х00, после записать данные, если есть после данные также дописать

**Comment by pimnik98** [comment]
> 
> Но код не работает потому что ФС не поддерживает  запись по смещению
> 

А разве не ос делать этот момент? Тип считать х байт и перезапись

**Comment by NDRAEY** [comment]
Ну там так и есть fseek - передвинуться куда-то и fwrite и записать столько то байт сюда

**Comment by NDRAEY** [comment]
Я манал это низкоуровневое программирование

**Comment by NDRAEY** [comment]
![17223473577886808462494996123568](https://github.com/user-attachments/assets/b43f3521-18f4-4ea7-aeb8-1955d8964853)
Бобрь курьва я кажись пофиксил

**Comment by NDRAEY** [comment]
Это на**й закрыто
