### ISSUE TITLE
🔌[Прочие] Поддержка SFF

### ISSUE THREAD

**Issue by pimnik98** [pimnik98/SayoriOS#38]
Задача

Поддержка Sayori Font File

**Comment by pimnik98** [comment]
А смысл теперь делать после появления PSF?

**Comment by NDRAEY** [comment]
Ага

**Comment by pimnik98** [comment]
![xP2fQN8fuMI.jpg](https://user-images.githubusercontent.com/48570109/212466005-8af2e333-8003-4b91-8d60-849dd1396a5c.jpg)

**Comment by pimnik98** [comment]
SFF1 - Первого поколения появился в v0.3.2 (Сборка 1125)

**Comment by pimnik98** [comment]
Связанные вопросы: https://github.com/pimnik98/SayoriOS/issues/38

**Comment by pimnik98** [comment]
Закрыто. И удалено связи с переходом на PSF
