### ISSUE TITLE
📂 [Файлы] Переход по папкам вызывает #UD:Невалидный код

### ISSUE THREAD

**Issue by Twink4** [pimnik98/SayoriOS#40]
**Описание**
Что за ошибка?
UD -невалидный ко

**Воспроизведение**
Шаги воспроизведения ошибки:
1. Перейти 'cd /'
2. Ввести 'test.txt'
3. Нажать 'enter'
4. Увидеть ошибку

**Ожидаемое поведение**
Что вы ожидали увидеть?

**Скриншоты**
Если возможно, прикрепите сюда фотографии
![el_vEKkW-nU](https://user-images.githubusercontent.com/29516851/201509524-bd21d57c-03a1-4b5a-9e56-a5cea2373ffe.jpg)

**Среда:**
 - Железо(Эмулятор): VirtualBox 7
 - Время работы ОС: минуты две
 - Версия ядра 0.3.0

**Дополнительная информация**
Любая другая информация о ошибке
[sai.log](https://github.com/pimnik98/SayoriOS/files/9996621/sai.log)

**Comment by NDRAEY** [comment]
Временный фикс в v0.3.2

**Comment by NDRAEY** [comment]
!!!

**Comment by pimnik98** [comment]
Решено в v0.3.2
