### ISSUE TITLE
📂 [Файлы] Просмотр файла, вызывает #PF:Переполнение памяти буфера

### ISSUE THREAD

**Issue by Twink4** [pimnik98/SayoriOS#41]
**Описание**
Что за ошибка? - PF - переполнение памяти буфера

**Воспроизведение**
Шаги воспроизведения ошибки:
1 - Запуск ядра
2 - make.sh
3 - ошибка

**Ожидаемое поведение**
Что вы ожидали увидеть?

**Скриншоты**
Если возможно, прикрепите сюда фотографии
![image](https://user-images.githubusercontent.com/29516851/201509668-83e81404-a715-48f9-af8b-deeb41adb4f4.png)

**Среда:**
 - Железо(Эмулятор): VirtualBox
 - Время работы ОС: 1min
 - Версия ядра 0.3.0

**Дополнительная информация**
Любая другая информация о ошибке
[sai.log](https://github.com/pimnik98/SayoriOS/files/9996628/sai.log)

**Comment by pimnik98** [comment]
Проблема связана с #40
При переходе по папкам есть небольшая порча памяти, из-за этого вылетает стек.

Скорее всего при решении проблемы #40 , решиться и эта проблема

**Comment by NDRAEY** [comment]
Пока что нет поддержки запуска скриптов .sh в командной строке.

**Comment by NDRAEY** [comment]
Поэтому и вылетает с ошибкой
