### ISSUE TITLE
💫 [Драйвера] Клавиатура игнорирует некоторые нажатия

### ISSUE THREAD

**Issue by NDRAEY** [pimnik98/SayoriOS#42]
**Описание**
Древняя ошибка игнорирующая некоторые клавиши. Была исправлена но только в функции getCharKeyboardWait

**Воспроизведение**
1. Очень быстро набирать текст без пробелов
2. Увидеть в шелле ошибку команда не найдена, это нормально. Но в сообщении ошибки у команды не хватает нескольких символов.

**Ожидаемое поведение**
Все буквы на своих местах

**Среда:**
 - Железо(Эмулятор): Qemu 7.1.0
 - Время работы ОС: ???
 - Версия ядра: 0.3.0

**Дополнительная информация**
Сейчас ведутся работы по ликвидации ошибки

**Comment by NDRAEY** [comment]
Если все будет норм, то можно закрывать issue

**Comment by pimnik98** [comment]
А я потестить, пока не могу.
Если все норм, закроем при выпуске обновы v0.3.1

**Comment by NDRAEY** [comment]
Хорошо

**Comment by pimnik98** [comment]
Решено в v0.3.1
#47
