### ISSUE TITLE
💫 [Драйвера] Драйвер звука SoundBlaster 16

### ISSUE THREAD

**Issue by NDRAEY** [pimnik98/SayoriOS#48]
Пока что есть звук на PC Speaker. Но он воспроизводит только тоны квадратной формы на некоторое время.
Эра цифрового звука!
SoundBlaster 16 не использует PCI, а значит его драйвер легко написать.

Он использует ISA DMA (Direct Memory Access) драйвер которого тоже необходимо написать.

**Comment by pimnik98** [comment]
Запрос #49 - Связан с текущим

**Comment by pimnik98** [comment]
Обновил теги

**Comment by NDRAEY** [comment]
Как поставить метку "устарело"?

**Comment by pimnik98** [comment]
Поставил метку, что не будет реализовано.

Если кто-то желает заняться, милости просим :)
