### ISSUE TITLE
💫 [Драйвера] ISA DMA (Direct Memory Access)

### ISSUE THREAD

**Issue by NDRAEY** [pimnik98/SayoriOS#49]
https://wiki.osdev.org/ISA_DMA

**Comment by pimnik98** [comment]
Обновил теги

**Comment by pimnik98** [comment]
Ну как дела с DMA?

**Comment by pimnik98** [comment]
Висит статус в процессе, таки он сделан или нет?
Просто какая причина закрытия Запроса?

**Comment by NDRAEY** [comment]
Не рентабельно. ISA DMA только для SB16 а у нас уже есть AC'97

**Comment by pimnik98** [comment]
OK

Поставил метку, что не будет реализовано.

Если кто-то желает заняться, милости просим :)
