### ISSUE TITLE
🔌 [Прочие] Нет некоторых символов в шрифтах

### ISSUE THREAD

**Issue by NDRAEY** [pimnik98/SayoriOS#51]
Отсутствуют некоторые символы ( < и > )
Из-за этого командная строка отображает не всё.

Должно быть: `user@oem:/>`
Пропадает `>`: `user@oem:/  `

**Comment by pimnik98** [comment]
Решено с переходом на PSF

**Comment by pimnik98** [comment]
#38

**Comment by pimnik98** [comment]
После перехода на PSF проблема решена.
