### ISSUE TITLE
‍💫 [Драйвера] Драйвер AC'97

### ISSUE THREAD

**Issue by NDRAEY** [pimnik98/SayoriOS#52]
Но только после PCI

**Comment by pimnik98** [comment]
PCI в Bone вообще сломанный
в VMWare крашиться при старте ОС

**Comment by NDRAEY** [comment]
Завтра посмотрю баг

**Comment by pimnik98** [comment]
Ну как оно?

**Comment by NDRAEY** [comment]
Я ещё не подключал PCI)))

**Comment by pimnik98** [comment]
Ну оно же есть с костяшки

**Comment by NDRAEY** [comment]
Да, с костяшки

**Comment by pimnik98** [comment]
> Да, с костяшки

Таки в чем проблема?

**Comment by NDRAEY** [comment]
VirtualBox на Линукс когда у тебя стоит кланг вообще жопная идея, VBox ставит в зависимости гцц и потом перезаписывается ссылка на cc и компилятор при сборке становится не тот.

**Comment by NDRAEY** [comment]
> > Да, с костяшки
> 
> Таки в чем проблема?

Лень

**Comment by NDRAEY** [comment]
Ну, можно сказать наполовину готово, потому что на VirtualBox не запускается, а с QEMU все работает
