### ISSUE TITLE
❤ [Ядро] strcmp() падает на строках с русскими буквами

### ISSUE THREAD

**Issue by NDRAEY** [pimnik98/SayoriOS#55]
**Описание**
Что за ошибка?
Ошибка и точка.
Краш с кодом #UD "Невалидный код"

**Воспроизведение**
Шаги воспроизведения ошибки:
В командной строке ввести что нибудь по-русски (чтобы включить русский язык надо нажать F1)

**Ожидаемое поведение**
Ошибка что команда не найдена

**Среда:**
 - Четверг

**Comment by pimnik98** [comment]
-Да, я слышал про четверг, но как вам пятница?
![IMG_20230108_090928_605.jpg](https://user-images.githubusercontent.com/48570109/211183069-ff97039c-5303-4f5c-9c55-1c0eaa89d0df.jpg)

**Comment by NDRAEY** [comment]
Нормааааааааана

**Comment by NDRAEY** [comment]
Возможно исправлено в v0.3.2
