### ISSUE TITLE
🔌 [Прочие] Не совпадают версии в grub и самой ОС

### ISSUE THREAD

**Issue by sal1r** [pimnik98/SayoriOS#57]
Скачал последний релиз 0.3.1. В grub версия 0.3.0, а на "экране смерти" 0.3.1

**Comment by pimnik98** [comment]
Исправлено в v0.3.2

**Comment by NDRAEY** [comment]
А когда можно будет закрыть иссу

**Comment by pimnik98** [comment]
> А когда можно будет закрыть иссу

Когда будет выпущен релиз
