### ISSUE TITLE
📦 [ПО] CPUInfo вызывает утечку памяти

### ISSUE THREAD

**Issue by pimnik98** [pimnik98/SayoriOS#58]
**Описание**
CPUInfo вызывает утечку памяти

**Воспроизведение**
Запустить несколько раз `cpuinfo`

**Ожидаемое поведение**
Норм реакцию, а оно копирует в самого себя и крашит ядро

**Среда:**
 - QEMU
 - Версия ядра SayoriOS Soul v0.2.13

**Comment by pimnik98** [comment]
Решено в v0.3.2

**Comment by NDRAEY** [comment]
!!!
