### ISSUE TITLE
🚫 [DevMgr-CLI] Не всегда реагирует на команды

### ISSUE THREAD

**Issue by pimnik98** [pimnik98/SayoriOS#6]
При вводе команд, куда-то вечно исчезает строка, из-за чего команда не выполняется.
Находиться на рассмотрении.

**Comment by NDRAEY** [comment]
Не наблюдается в v0.3.2

**Comment by pimnik98** [comment]
Device Manager не поставляется в редакции Soul.
Причина: необходимо переписать методику работы

**Comment by NDRAEY** [comment]
!!!

**Comment by NDRAEY** [comment]
Если DevMgr не планируется в Soul, то можно закрыть этот issue
