### ISSUE TITLE
💻 Запуск на ASUS P5AD2-E Premium

### ISSUE THREAD

**Issue by pimnik98** [pimnik98/SayoriOS#60]
💻 Наш подопытный:
* Плата: ASUS P5AD2-E Premium
* Процессор: Intel Pentium 4 511 1x3.8 Ггц (Разгон)
* Оперативная память: 2х512 MB DDR2 533 Mhz
* Жесткий диск: WDC WD1600JS-00NCB1 (160 GB, 7200 RPM, Sata II)
* Видеокарта: NVIDIA GT 7300 GT (256 MB DDR2, 350 Mhz)
* Звук 8-канальный HDA кодек C-Media CMI9880
* Дополнительно: (✔Socket LGA775 ✔Intel 925XE ✔1 слот 16x PCI-E ✔Нет видеовыходов ✔RAID-контроллер ✔ATX ✔ДО 4x DDR2 ✔1x LPT ✔ 1x IEEE1394 (6-pin))

💽 Система:
* SayoriOS Soul v0.3.2 build 1127

📒 Заметки:
* Очень долгий старт (около пяти минут)
* Очень медленная работа с памятью

✅ Результат:
* ОС Запустилась
* Работали USB-Клавиатура и USB-Мышь
![SayoriOS](https://user-images.githubusercontent.com/48570109/215205468-93a3edc7-15a7-476e-a37d-1563cb9af9b4.png)
![SayoriOS](https://user-images.githubusercontent.com/48570109/215205491-f09c3926-17bf-45ca-8373-3de5a44c9be5.png)
![Panic](https://user-images.githubusercontent.com/48570109/215205508-487b8dd7-e99c-4185-a274-124ef954696f.png)
![Config](https://user-images.githubusercontent.com/48570109/215205522-46137c3c-fb6a-4f79-b986-4b0b6796569f.png)
![CPUInfo](https://user-images.githubusercontent.com/48570109/215205534-3d06832d-913d-43ac-9692-72d1c15bdee2.png)

[Запись+видео в ВК](https://vk.com/sayorios?w=wall-213841039_116)

**Comment by NDRAEY** [comment]
А с этими штуками что делать?
